# Description: MetalLB load balancer for bare-metal Kubernetes clusters
# Category: networking
# Version: v0.14.8
# Dependencies: none
# Maintainer: CPC Team

---
- name: Install/Upgrade MetalLB
  when: addon_name in ['metallb', 'all']
  delegate_to: "{{ groups['control_plane'][0] }}"
  block:
    - name: Set MetalLB version
      ansible.builtin.set_fact:
        metallb_target_version: >-
          {{ requested_version if requested_version != '' else (metallb_version | default('v0.14.8')) }}

    - name: Check current MetalLB version
      ansible.builtin.shell: kubectl get pods -n metallb-system -o jsonpath='{.items[0].spec.containers[0].image}' | cut -d':' -f2
      register: current_metallb_version
      ignore_errors: true

    - name: Apply MetalLB native manifests
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ metallb_target_version }}/config/manifests/metallb-native.yaml
      register: metallb_apply_result
      changed_when: "'configured' in metallb_apply_result.stdout or 'created' in metallb_apply_result.stdout"

    - name: Wait for MetalLB pods to be ready
      ansible.builtin.shell: kubectl wait --for=condition=ready pod -l app=metallb -n metallb-system --timeout=300s
      changed_when: false

    - name: Create MetalLB IP pool configuration
      ansible.builtin.shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: default-pool
          namespace: metallb-system
        spec:
          addresses:
          - 10.10.10.200-10.10.10.220
        ---
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: default-l2advertisement
          namespace: metallb-system
        spec:
          ipAddressPools:
          - default-pool
        EOF
      register: metallb_config_result
      changed_when: "'configured' in metallb_config_result.stdout or 'created' in metallb_config_result.stdout"

    - name: Verify MetalLB installation
      ansible.builtin.shell: kubectl get pods -n metallb-system --no-headers | grep -c "Running"
      register: metallb_final_check
      changed_when: false

    - name: Display MetalLB installation result
      ansible.builtin.debug:
        msg:
          - "MetalLB installation completed"
          - "Previous version: {{ current_metallb_version.stdout | default('unknown') }}"
          - "Current version: {{ metallb_target_version }}"
          - "Running pods: {{ metallb_final_check.stdout }}"
