name: 🐛 Bug Report
description: Report a bug to help us improve CPC
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command `./cpc ...`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core CPC commands
        - Proxmox module
        - K8s cluster module
        - K8s nodes module
        - Cluster operations module
        - DNS/SSL module
        - Documentation
        - Testing framework
        - Other
    validations:
      required: true

  - type: input
    id: cpc-version
    attributes:
      label: CPC Version
      description: What version of CPC are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your environment
      placeholder: |
        OS: Ubuntu 22.04
        Proxmox VE: 8.1
        OpenTofu: 1.6.0
        Ansible: 2.14.0
        Python: 3.11.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Output
      description: Relevant logs, error messages, or output
      render: shell
      placeholder: Paste relevant logs here
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration files (remove sensitive data)
      render: yaml
      placeholder: Paste relevant configuration here
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have tested with the latest version
          required: false
        - label: I have included relevant logs and output
          required: false
        - label: I have removed sensitive information from logs and config
          required: true
