name: ✨ Feature Request
description: Suggest a new feature or enhancement for CPC
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details about your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature
      placeholder: A concise summary of the proposed feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions you've considered
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Core CPC commands
        - Proxmox module
        - K8s cluster module
        - K8s nodes module
        - Cluster operations module
        - DNS/SSL module
        - Documentation
        - Testing framework
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: How would you use this feature in practice?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      placeholder: |
        Example commands, configuration, or workflows
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: Screenshots, links to similar features in other tools, etc.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: This feature aligns with CPC's goals and scope
          required: true
        - label: I have considered the complexity and maintenance burden
          required: false
        - label: I am willing to help implement this feature
          required: false
