---
# vars file for setup_kubernetes_cluster role (Debian family)

containerd_prerequisites_packages:
  - ca-certificates
  - curl
  - gnupg

docker_gpg_key_url_debian: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_gpg_key_path_debian: "/etc/apt/keyrings/docker.asc"
docker_repo_url_debian: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"

k8s_gpg_key_path_debian: "/etc/apt/keyrings/kubernetes-apt-keyring.asc"
