# Description: Kubernetes Metrics Server for resource monitoring
# Category: monitoring
# Version: v0.7.2
# Dependencies: none
# Maintainer: CPC Team

---
- name: Install/Upgrade Metrics Server
  when: addon_name in ['metrics-server', 'all']
  delegate_to: "{{ groups['control_plane'][0] }}"
  block:
    - name: Set Metrics Server version
      ansible.builtin.set_fact:
        metrics_server_target_version: >-
          {{ requested_version if requested_version != '' else (metrics_server_version | default('v0.7.2')) }}

    - name: Check current Metrics Server version
      ansible.builtin.shell: kubectl get deployment -n kube-system metrics-server -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d':' -f2
      register: current_metrics_server_version
      ignore_errors: true

    - name: Download Metrics Server manifests
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/kubernetes-sigs/metrics-server/096960107da4a1b2e2ec83b2ac3424248cfc0ad5/deploy/kubernetes/components.yaml"
        dest: "/tmp/metrics-server-{{ metrics_server_target_version }}.yaml"
        mode: '0644'
    - name: Apply Metrics Server manifests
      ansible.builtin.shell: kubectl apply -f /tmp/metrics-server-{{ metrics_server_target_version }}.yaml
      register: metrics_server_apply_result
      changed_when: "'configured' in metrics_server_apply_result.stdout or 'created' in metrics_server_apply_result.stdout"

    - name: Patch Metrics Server for self-hosted clusters
      ansible.builtin.shell: |
        # WARNING: --kubelet-insecure-tls disables TLS verification between metrics-server and kubelets
        # This is a security risk and should only be used in non-production self-hosted clusters
        # For production environments, configure proper CA-signed certificates for kubelets
        kubectl patch deployment metrics-server -n kube-system --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-insecure-tls"}]' || true
      when: metrics_server_apply_result.changed

    - name: Wait a moment for resources to be created
      ansible.builtin.pause:
        seconds: 5

    - name: Wait for Metrics Server deployment to be created
      ansible.builtin.shell: kubectl wait --for=jsonpath='{.status.observedGeneration}'=1 deployment/metrics-server -n kube-system --timeout=60s
      changed_when: false
      ignore_errors: true

    - name: Wait for Metrics Server pods to be created
      ansible.builtin.shell: kubectl wait --for=jsonpath='{.items[*].status.phase}'=Running pod -l k8s-app=metrics-server -n kube-system --timeout=60s
      changed_when: false
      ignore_errors: true

    - name: Wait for Metrics Server to be ready
      ansible.builtin.shell: kubectl wait --for=condition=ready pod -l k8s-app=metrics-server -n kube-system --timeout=300s
      changed_when: false

    - name: Verify Metrics Server upgrade
      ansible.builtin.shell: kubectl get deployment -n kube-system metrics-server -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d':' -f2
      register: new_metrics_server_version
      changed_when: false

    - name: Display Metrics Server upgrade result
      ansible.builtin.debug:
        msg:
          - "Metrics Server upgrade completed"
          - "Previous version: {{ current_metrics_server_version.stdout | default('unknown') }}"
          - "Current version: {{ new_metrics_server_version.stdout }}"
