---
- name: Approve Pending Kubelet Serving CSRs
  hosts: control_plane
  become: yes
  gather_facts: no
  tasks:
    - name: Check for pending kubelet serving CSRs
      ansible.builtin.shell: kubectl get csr --no-headers | grep "kubelet-serving" | grep "Pending" | wc -l
      register: pending_csr_count
      changed_when: false
      ignore_errors: true

    - name: List pending kubelet serving CSRs
      ansible.builtin.shell: kubectl get csr | grep "kubelet-serving" | grep "Pending"
      register: pending_csr_list
      changed_when: false
      ignore_errors: true
      when: pending_csr_count.stdout|int > 0

    - name: Display pending CSRs
      ansible.builtin.debug:
        msg: |
          Found {{ pending_csr_count.stdout }} pending kubelet serving CSRs:
          {{ pending_csr_list.stdout }}
      when: pending_csr_count.stdout|int > 0

    - name: Approve all pending kubelet serving CSRs
      ansible.builtin.shell: kubectl get csr -o name | grep "kubelet-serving" | xargs kubectl certificate approve
      when: pending_csr_count.stdout|int > 0
      register: csr_approval_result
      changed_when: true

    - name: Display approval result
      ansible.builtin.debug:
        msg: |
          CSR Approval Result:
          {{ csr_approval_result.stdout }}
      when: pending_csr_count.stdout|int > 0 and csr_approval_result is defined

    - name: No pending CSRs message
      ansible.builtin.debug:
        msg: "No pending kubelet serving CSRs found."
      when: pending_csr_count.stdout|int == 0

    - name: Verify all CSRs are approved
      ansible.builtin.shell: kubectl get csr | grep "kubelet-serving"
      register: final_csr_status
      changed_when: false
      ignore_errors: true

    - name: Display final CSR status
      ansible.builtin.debug:
        msg: |
          Final kubelet serving CSR status:
          {{ final_csr_status.stdout }}
      when: final_csr_status.stdout != ""
