# ansible/playbooks/pb_delete_node.yml

- name: Delete Node from Kubernetes Cluster
  hosts: all
  become: yes
  tasks:
    - name: Drain the node before deletion
      command: kubectl drain {{ inventory_hostname }} --ignore-daemonsets --delete-emptydir-data
      delegate_to: "{{ groups['control_plane'][0] }}"
      run_once: true

    - name: Delete the node from the cluster
      command: kubectl delete node {{ inventory_hostname }}
      delegate_to: "{{ groups['control_plane'][0] }}"
      run_once: true

    - name: Reset the node
      command: kubeadm reset --force
