# ansible/playbooks/traefik-values.yaml

# 1. Явно включаем нужные нам провайдеры
providers:
  kubernetesGateway:
    enabled: true
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

# 2. Включаем DEBUG логи для диагностики
log:
  level: INFO

# 3. Включаем Dashboard
dashboard:
  enabled: true

# 4. Настраиваем Gateway API
experimental:
  kubernetesGateway:
    enabled: true
    gateway:
      service:
        type: LoadBalancer


# 5. Настраиваем точки входа (порты)
entryPoints:
  websecure:
    address: ":8443/tcp"
    # Говорим Traefik, что ждем PROXY protocol от Nginx
    proxyProtocol:
      insecure: true

# 6. Настраиваем сервис Kubernetes
service:
  annotations:
    # This will tell DigitalOcean to enable the proxy protocol so we can get the client real IP.
    service.beta.kubernetes.io/linode-loadbalancer-enable-proxy-protocol: "true"
  ports:
    websecure:
      port: 443
      targetPort: 8443

additionalArguments:
  - --entryPoints.web.proxyProtocol.insecure=true
  - --entryPoints.websecure.proxyProtocol.insecure=true

