---
# handlers file for setup_kubernetes_cluster

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  listen: Restart containerd

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  listen: Update apt cache

- name: Hold Kubernetes packages Debian
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  when: ansible_os_family == "Debian"
  listen: Hold Kubernetes packages Debian

- name: Ensure dnf versionlock plugin is installed (RedHat)
  ansible.builtin.package:
    name: 'dnf-command(versionlock)' # For RHEL 8+/Rocky 8+
    state: present
  when: ansible_os_family == "RedHat"
  listen: Hold Kubernetes packages RedHat # Run before trying to lock

- name: Hold Kubernetes packages RedHat
  ansible.builtin.command: "dnf versionlock add {{ item }}{{ k8s_pkg_version_string_redhat if kubernetes_patch_version == 'latest' else ('-' + kubernetes_patch_version if kubernetes_patch_version is defined else '') }}"
  loop:
    - kubelet
    - kubeadm
    - kubectl
  when: ansible_os_family == "RedHat"
  changed_when: true # Assume lock command makes a change
  listen: Hold Kubernetes packages RedHat
