// File: internal/tofu/generator.go
package tofu

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/abevz/createpersonalcluster/cpc-go/internal/config"
)

const backendTfTemplate = `terraform {
  backend "s3" {
    endpoint                     = "{{ .Endpoint }}"
    bucket                       = "{{ .Bucket }}"
    key                          = "{{ .Key }}"
    region                       = "{{ .Region }}"
    access_key                   = "{{ .AccessKey }}"
    secret_key                   = "{{ .SecretKey }}"
    skip_credentials_validation  = {{ .SkipCredentialsValidation }}
    skip_metadata_api_check      = {{ .SkipMetadataApiCheck }}
    skip_region_validation       = {{ .SkipRegionValidation }}
    use_path_style               = {{ .UsePathStyle }}
  }
}
`

// GenerateFiles creates all necessary files for OpenTofu in a temporary directory.
func GenerateFiles(cfg *config.Deployment, workDir string) error {
	/*
		* if err := generateBackend(cfg, workDir); err != nil {
				return fmt.Errorf("error generating backend.tf: %w", err)
			}
	*/
	if err := generateTvars(cfg, workDir); err != nil {
		return fmt.Errorf("error generating terraform.tfvars.json: %w", err)
	}

	/*
		  mainTfContent := "# main.tf file generated by cpc-go\n# TODO: Add dynamic resource generation"
			if err := os.WriteFile(filepath.Join(workDir, "main.tf"), []byte(mainTfContent), 0o644); err != nil {
				return fmt.Errorf("error creating main.tf: %w", err)
			}
	*/

	return nil
}

func generateTvars(cfg *config.Deployment, workDir string) error {
	var err error
	switch cfg.Spec.TfvarsSchema {
	case "v2":
		log.Println("Generating terraform.tfvars.json using new schema (v2)...")
		err = generateTfvarsV2(cfg, workDir)
	default:
		log.Println("Generating terraform.tfvars.json using legacy schema (v1)...")
		err = generateTfvarsV1(cfg, workDir)
	}
	if err != nil {
		return err
	}
	log.Println("File terraform.tfvars.json generated successfully.")
	return nil
}

func generateTfvarsV1(cfg *config.Deployment, workDir string) error {
	tfvars := make(map[string]interface{})

	// --- Provider Credentials & Config ---
	tfvars["proxmox_password"] = cfg.ProviderCredentials.Proxmox["password"]
	if providerConfig, ok := cfg.Spec.ProviderConfig["proxmox"].(map[string]interface{}); ok {
		for key, val := range providerConfig {
			if key == "node" {
				tfvars["pm_node"] = val
			} else {
				tfvars["proxmox_"+key] = val
			}
		}
	}

	// --- Cluster Basics ---
	tfvars["cluster_id"] = cfg.Metadata.Name
	tfvars["cluster_domain"] = cfg.Spec.ClusterDomain

	// --- NEW: Universal variables from deployment.yaml ---
	// This replaces the hardcoded release_letter
	if cfg.Spec.Variables != nil {
		for key, val := range cfg.Spec.Variables {
			tfvars[key] = val
		}
	}

	// --- Node Group Processing ---
	var additionalControlPlanes []string
	var additionalWorkers []string
	for _, group := range cfg.Spec.NodeGroups {
		baseCount := 0
		if group.Name == "control-plane" {
			baseCount = 1
		} else if group.Name == "workers" {
			baseCount = 2
		}
		if group.Count > baseCount {
			for i := baseCount + 1; i <= group.Count; i++ {
				singularName := strings.TrimSuffix(group.Name, "s")
				nodeName := fmt.Sprintf("%s-%d", singularName, i)
				if group.Name == "control-plane" {
					additionalControlPlanes = append(additionalControlPlanes, nodeName)
				} else if group.Name == "workers" {
					additionalWorkers = append(additionalWorkers, nodeName)
				}
			}
		}
	}
	tfvars["additional_controlplanes"] = strings.Join(additionalControlPlanes, ",")
	tfvars["additional_workers"] = strings.Join(additionalWorkers, ",")

	// --- Final JSON Generation ---
	return writeTfvarsFile(tfvars, workDir)
}

func generateTfvarsV2(cfg *config.Deployment, workDir string) error {
	tfvars := make(map[string]interface{})
	tfvars["proxmox_password"] = cfg.ProviderCredentials.Proxmox["password"]
	if providerConfig, ok := cfg.Spec.ProviderConfig["proxmox"].(map[string]interface{}); ok {
		for key, val := range providerConfig {
			tfvars["proxmox_"+key] = val
		}
	}
	var allNodes []map[string]interface{}
	for _, group := range cfg.Spec.NodeGroups {
		for i := 1; i <= group.Count; i++ {
			node := make(map[string]interface{})
			node["name"] = fmt.Sprintf("%s-%d", group.Name, i)
			node["hostname"] = fmt.Sprintf("%s%d.%s", group.RolePrefix, i, cfg.Spec.ClusterDomain)
			node["role"] = group.Name
			node["profile"] = group.Profile
			allNodes = append(allNodes, node)
		}
	}
	tfvars["nodes"] = allNodes
	return writeTfvarsFile(tfvars, workDir)
}

func writeTfvarsFile(tfvars map[string]interface{}, workDir string) error {
	tfvarsJSON, err := json.MarshalIndent(tfvars, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal tfvars to JSON: %w", err)
	}
	return os.WriteFile(filepath.Join(workDir, "terraform.tfvars.json"), tfvarsJSON, 0o644)
}

// CORRECTED VERSION of generateBackend
/*
* func generateBackend(cfg *config.Deployment, workDir string) error {
	type BackendData struct {
		Endpoint                  string
		Bucket                    string
		Key                       string
		Region                    string
		AccessKey                 string
		SecretKey                 string
		SkipCredentialsValidation bool
		SkipMetadataApiCheck      bool
		SkipRegionValidation      bool
		UsePathStyle              bool
	}

	// Safely access map values with type assertion
	data := BackendData{
		Endpoint:                  fmt.Sprintf("%v", cfg.TofuBackend.Config["endpoint"]),
		Bucket:                    fmt.Sprintf("%v", cfg.TofuBackend.Config["bucket"]),
		Key:                       fmt.Sprintf("%v", cfg.TofuBackend.Config["key"]),
		Region:                    fmt.Sprintf("%v", cfg.TofuBackend.Config["region"]),
		SkipCredentialsValidation: cfg.TofuBackend.Config["skip_credentials_validation"].(bool),
		SkipMetadataApiCheck:      cfg.TofuBackend.Config["skip_metadata_api_check"].(bool),
		SkipRegionValidation:      cfg.TofuBackend.Config["skip_region_validation"].(bool),
		UsePathStyle:              cfg.TofuBackend.Config["use_path_style"].(bool),
		AccessKey:                 cfg.S3BackendCredentials.AccessKey,
		SecretKey:                 cfg.S3BackendCredentials.SecretKey,
	}

	tmpl, err := template.New("backend").Parse(backendTfTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse backend template: %w", err)
	}

	file, err := os.Create(filepath.Join(workDir, "backend.tf"))
	if err != nil {
		return fmt.Errorf("failed to create backend.tf file: %w", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("failed to execute backend template: %w", err)
	}

	// This was the missing part - the success message and return should be here
	log.Println("File backend.tf generated successfully.")
	return nil
}
*/
